* Отказоустойчивые ПК

Серверный структуры - FT(Fault tolerant)

В приницпе не падают, то есть некая апаратная избыточность.

В основу FT серверов, лежит задублированность элементов.

В разных серверах, элементы могут быть задублированы.

------

Каждый задублированный элемент, способен продолжать свою работу, в случае отказа своего партнёра

В таком случае, система не почуствует отказа, одного из компонентов, при этом функционирование не ухудшится.

..., то система диагностирует неисправность программного модуля.

# Что же там в 3 точках, загадка)

И автоматически его изолирует. При этом партнёры продолжают работу до тех пор, пока неисправный элемент, не начнёт работать
в исправном режиме.

**Постоянная доступность**

Сервера имеют на своём борту системы Unix, при этом ОС у них модифицированы --> Оказоустойчивые операциоонные системы.

1. Открытость
2. Масштабированность
3. Надёжность - аппратно. Простой - пару минут в год
4. Цена - дорогая, лучше купить кластер. Но дополнительных затрат на обслуживающий персонал становится меньше.
5. Отсутствуют затраты, на планирование возможных сбоев, на модификацию сценариев

