* Отказоустойчевость компьютерных систем

Наработка на отказ - время в течение которого, наш элемент или система 
будет работать без поломок, без отказов

HDD - срок действие механики

Существует несколько варинтов повышение надежности:

1. Аппаратурный -> присутствует аппаратурная ибыточность(много дублирующего оборудования):
   - Все операции паралельны на всех одинаковых компонентах -> все операции сравниваются между собой,
     что позволяет выявить ошибки
   - В случае возникновения ошибок/неисправностей "партнер" выполняет все необходимые действия до того
     момента, пока не будет заменен неисправный компонент

[[   https://mermaid.ink/img/pako:eNpdkEFqAjEUQK8S_loX6m4WLkRPYFcaF8F864CTDDGzEBGsxZWFgiewN5hFpaXt9Aw_N_Ib0RYXIe_By4efJYytRkjg0al8Kh660gghesajG9I-bOmX3qkKOzoKhpKqi4xEvd4Wjb84evPOW9EbkTtDeqPP8BQ2dKQfKgV98ewqbMKa7-_wOopx8xJHbv3jTmQ68OOP8Mz9Cw8qz0caqEGGLlOp5j2W51yCn2KGEhJGjRNVzLwEaVacFrlWHns69dZBMlGzOdZAFd72F2YMiXcFXqNuqvhbsluVKzOw9uqrE88wfyQ]]

   Троированная мажоритарная система контроля -> Чем больше одинаковых - то и верно
   Если все ответы разные -> то нет верного ответа --> ERROR

   Используется в системах, где требуется высокая отказоустойчивость
   Недостаток: высокая стоимость

2. Программный
   - Одновременная работа нескольких машин
   - Дублирование данных и процессов
   - Процедуры автоматического восстановления, касающихся ОС данных и приложений

На данный момент многие системы Апп. и Прог. повышения надежности сравнимы между собой

Надежность системы рассматривается с точки зрения 2-х критериев:
 - Доступность системы
 - Целостность данных

   
**Управляемость системы** включает:
 - Замена неисправных частей незаметно для системы в целом
 - Непрерывное функционирование системы в 3-х основных случаях:
   1) Сбой системы(отказ)
   2) Изменение конфигурации
   3) Расширение системы
 - Эффективное управление массивами данных с большими объемами   
 - Эффективная обработка очередей и распределения нагрузки   
 - Созранение и архивация данных в режиме онлайн
 - Мониторинг работы системы
 - Как можно более раннее обнаружение и локализация ошибок
   (например, smart)

** Способы повышения надежности

1. **Raid massive** - избыточный массив недорогих дисков
   Предназначен для защиты данных при выходе из строя магнитных дисков
2. Отказы других физ. компонентов можно корректировать другими способами:
   - **Дублирование**
   - Установка доп. оборудования поддержки
   Сюда же относятся бесперебойные источники питания, а также стабилизаторы
   (ИБП UPS), (аккумуляторные или дизель-генераторные установки)
3. **Кластеризация** - используется несколько компьютеров, которые обычно соединяются
   в сеть при этом имеющие общие ресурсы(к примеру, дисковое пространство)
   Имеет единую файловую систему, а для пользователя выглядит не как распределенная,
   а как единая система. Это достигается при помощи спец ПО(оно координируте
   передачу всей инфо, а также ее обработку)
   Отдельный компьютер кластера - **узел**
   Если один из узлов выходит из строя, то его нагрузку берет на себя другой узел
   кластера, или распределяется между остальными
   При замене отказавшего элемента кластеры автоматически перераспределят нагрузку

   ПО кластера:
   1) Программа обеспечивающая непротиворечивость доступа приложения
   2) Утилиты мониторинга и конфигурирования кластера
   3) Утилиты конфигурирования ФС и программы управления дисковым пространством

   Св-ва кластеров:
   1) **Открытость** (в некотрых случаях софт под кластера расчитан под определенные
      задачи. Т.е. подержка одной аппаратной платформы)
   2) **Масштабируемость** - в основном подразумевается добавление кластера с
      расширением ресусров
      В случае сбоя в системе кластера, кластеры действуют по схожему алгоритму:
      1) Определяет отказ
      2) Формирование нового кластера
      3) Запуск сценариев
      4) Тестирование ФС
      5) Запуск БД, встроенной в кластер
      6) Восстановление БД (если нужно)
      7) Перезапуск приложения

      В случае серьезного отказа (отказал один из узлов) (при этом некоторые приложения
      могут оказаться недоступны, в течение времени необходимого для переключения на
      другой узел)
      
   3) **Управляемость**.

      Запись и архивация в бд происходят в режиме реального времени
      RTS - real time system - в состав RTS вхдят бд, умеющие работать в онлайн режиме
      Запись и архивация происходит в несколько копий сразу
      Поиск и локализация ошибок будет производиться программным методом

   4) **Стоимость**
      Что нужно учитывать:
      - Стоимость доп. оборудования
      - Тестирование самой системы
      - Планирование работы кластера и изменение в его работе
      - Планирование всех возможных событий
      - Подготовка документации на кластер
      - Оплата консультантов
      - Обучение персонала
      
